Update and make more user friendly to README.md
davidchocholaty/bithack_hackaton_2024 pull request #3
Opened 2024-10-15 19:45 UTC by ayush-pandey047

I have make README.md more attractive and added emoji. The plus point is that I added link on data.Brno, as it will help user to know about data.Brno if they don't know about it. I also added more content in it. 

if you like my work so accept this because it will motivate.(Hacktoberfest-accepted)

2024-10-15 21:33 UTC, davidchocholaty requested changes
Thank you very much for contributing to this repository and for your suggestions to improve the README. I really like them overall. However, please remove the "Project Highlights" and "App Preview" sections, and then I'll be happy with the changes. Once those updates are made, I will label the PR as _hacktoberfest-accepted_ and merge it.

2024-10-15 21:33 UTC, davidchocholaty commented on README.md
> +## 🛠️ Project Highlights
The `Project Highlights` part is IMHO not needed. Please remove this part.

2024-10-15 21:33 UTC, davidchocholaty commented on README.md
> +## 📱 App Preview
The same for the `App Preview`. Please remove this part too.

2024-10-16 03:25 UTC, ayush-pandey047 commented
I have updated your readme.md you can check it.

2024-10-16 09:42 UTC, ayush-pandey047 commented
I HAVE CHANGE AS PER YOUR NEEDS.

2024-10-16 11:48 UTC, davidchocholaty commented
Perfect, thank you! It looks good now, and the `hacktoberfest-accepted` label has already been set. The PR is ready to be merged. Thank you for your work.

2024-10-16 11:50 UTC, davidchocholaty approved these changes

2024-10-16 11:51 UTC, merged